### ISSUE TITLE
Missing source folder folseparators

### ISSUE THREAD

**Issue by aman-goel** [wilcoxjay/mypyvy#12]
I am trying to run the latest mypyvy version on branch pldi20-artifact (to try using the contents of this [paper](http://theory.stanford.edu/~aiken/publications/papers/pldi20.pdf)). I am seeing that the folder "folseparators" is missing in the current source. This is needed by the symbolically linked file [separators](https://github.com/wilcoxjay/mypyvy/blob/pldi20-artifact/src/separators).

It would be great if the missing source files can be released as well (so as to try these nice new techniques).

Thanks to all the developers of mypyvy.

--
[Aman](https://aman-goel.github.io/)

**Comment by jrkoenig** [comment]
Thank you for your interest in our work! We're working on getting the separation code ready for public release.

It will also be available from the ACM in the artifact for the PLDI20 paper, but I'm not sure what the timeline for publication is.

**Comment by aman-goel** [comment]
Thanks!
