### ISSUE TITLE
bmc trace lists states and transitions in reverse order

### ISSUE THREAD

**Issue by nano-o** [wilcoxjay/mypyvy#7]
Hello, I tried bmc on `lockserv_clean.pyv` after adding `invariant [bad] !holds_lock(N)` and got the following. It seems that the transitions are listed from first to last while the states are listed from last to first. I used the latest code on branch master.

```
bmc checking the following property up to depth 3
  forall N:node. !holds_lock(N)
found violation
sort node
  node0


state 0:
holds_lock(node0)

transition send_lock

state 1:
grant_msg(node0)

transition recv_lock

state 2:
lock_msg(node0)
server_holds_lock()

transition recv_grant

state 3:
server_holds_lock()
```

**Comment by wilcoxjay** [comment]
Thanks for the report! This was introduced during the old->new migration. I'm not sure what I was thinking when I added a `reversed` there, but at least it was a very easy fix.

Let me know if you have further trouble!
